//
// Generated file, do not edit! Created by nedtool 5.2 from inet/linklayer/aloha/ALOHAFrame.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __INET_ALOHAFRAME_M_H
#define __INET_ALOHAFRAME_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif

// cplusplus {{
    #include "inet/linklayer/base/MACFrameBase_m.h"
// }}


namespace inet {

/**
 * Class generated from <tt>inet/linklayer/aloha/ALOHAFrame.msg:36</tt> by nedtool.
 * <pre>
 * //
 * // A CSMA mac packet format definition
 * //
 * // \@author Daniel Willkomm
 * //
 * packet ALOHAFrame extends MACFrameBase
 * {
 *     long sequenceId; // Sequence Number to detect duplicate messages
 *     int frameSize;
 * }
 * </pre>
 */
class INET_API ALOHAFrame : public ::inet::MACFrameBase
{
  protected:
    long sequenceId;
    int frameSize;

  private:
    void copy(const ALOHAFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ALOHAFrame&);

  public:
    ALOHAFrame(const char *name=nullptr, short kind=0);
    ALOHAFrame(const ALOHAFrame& other);
    virtual ~ALOHAFrame();
    ALOHAFrame& operator=(const ALOHAFrame& other);
    virtual ALOHAFrame *dup() const override {return new ALOHAFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual long getSequenceId() const;
    virtual void setSequenceId(long sequenceId);
    virtual int getFrameSize() const;
    virtual void setFrameSize(int frameSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ALOHAFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ALOHAFrame& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_ALOHAFRAME_M_H

